<#
.SYNOPSIS
    Captures the dev environment - VS Code, installed programs, tool versions -
    into the migration bundle.

.DESCRIPTION
    Called by make-bundle.ps1, but runs standalone too. Writes an `environment\`
    folder containing:

        vscode\                    settings, keybindings, snippets, profiles
        vscode-extensions.txt      extension IDs, for bulk reinstall
        installed-programs.csv     everything in Add/Remove Programs
        reinstall-programs.ps1     winget script for the dev toolchain
        environment-report.md      versions, architecture, and the gotchas

    Programs themselves are NOT copied - Windows software can't be moved by
    copying files. What travels is the inventory plus a scripted reinstall.

.EXAMPLE
    .\capture-environment.ps1 -OutPath "C:\...\FPGod-Migration-2026-08-12\environment"
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$OutPath
)

$ErrorActionPreference = 'Stop'
function Ok   ($m) { Write-Host "  [ok] $m" -ForegroundColor Green }
function Warn ($m) { Write-Host "  [!]  $m" -ForegroundColor Yellow }

New-Item -ItemType Directory -Force -Path $OutPath          | Out-Null
New-Item -ItemType Directory -Force -Path "$OutPath\vscode" | Out-Null

# ------------------------------------------------------------------ vscode ---
$codeUser = "$env:APPDATA\Code\User"
$extCount = 0

if (Test-Path $codeUser) {
    foreach ($f in @('settings.json', 'keybindings.json')) {
        if (Test-Path "$codeUser\$f") { Copy-Item "$codeUser\$f" "$OutPath\vscode\$f" -Force; Ok "vscode/$f" }
    }
    foreach ($d in @('snippets', 'profiles')) {
        if (Test-Path "$codeUser\$d") {
            $n = @(Get-ChildItem "$codeUser\$d" -Recurse -File -ErrorAction SilentlyContinue).Count
            if ($n -gt 0) {
                Copy-Item "$codeUser\$d" "$OutPath\vscode\$d" -Recurse -Force
                Ok "vscode/$d ($n files)"
            }
        }
    }
}
else { Warn "no VS Code user folder found" }

# --list-extensions is the only reliable source; the extensions folder on disk
# includes orphans from updates.
if (Get-Command code -ErrorAction SilentlyContinue) {
    $ext = code --list-extensions --show-versions
    $ext | Set-Content "$OutPath\vscode-extensions.txt" -Encoding utf8
    $extCount = $ext.Count
    Ok "$extCount VS Code extensions listed"
}
else { Warn "code CLI not on PATH - extensions not captured" }

# -------------------------------------------------------- installed programs -
$regPaths = @(
    'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*',
    'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*',
    'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*'
)
$apps = Get-ItemProperty $regPaths -ErrorAction SilentlyContinue |
        Where-Object { $_.DisplayName -and -not $_.SystemComponent } |
        Select-Object DisplayName, DisplayVersion, Publisher -Unique |
        Sort-Object DisplayName
$apps | Export-Csv "$OutPath\installed-programs.csv" -NoTypeInformation -Encoding utf8
Ok "$($apps.Count) installed programs inventoried"

# ---------------------------------------------------- scripted reinstall ------
# Only the toolchain the app actually needs, plus the obvious daily drivers.
# winget IDs are stable; versions deliberately unpinned so the new PC gets current.
@'
# Reinstalls the development toolchain on a new PC.
# Run in an elevated PowerShell. Skips anything already present.
# Generated by capture-environment.ps1 - see installed-programs.csv for the
# full list of what was on the old machine, including firm-managed software
# that IT will need to provision instead.

$packages = @(
    @{ Id = 'Git.Git';                  Name = 'Git';            Required = $true  },
    @{ Id = 'OpenJS.NodeJS.LTS';        Name = 'Node.js LTS';    Required = $true  },
    @{ Id = 'PostgreSQL.PostgreSQL.18'; Name = 'PostgreSQL 18';  Required = $true  },
    @{ Id = 'Microsoft.VisualStudioCode'; Name = 'VS Code';      Required = $true  },
    @{ Id = 'Google.Chrome';            Name = 'Google Chrome';  Required = $false },
    @{ Id = 'Zoom.Zoom';                Name = 'Zoom Workplace'; Required = $false },
    @{ Id = 'Python.Launcher';          Name = 'Python Launcher';Required = $false }
)

foreach ($p in $packages) {
    $tag = if ($p.Required) { 'required' } else { 'optional' }
    Write-Host ""
    Write-Host "==> $($p.Name) [$tag]" -ForegroundColor Cyan
    winget list --id $p.Id --exact | Out-Null
    if ($LASTEXITCODE -eq 0) {
        Write-Host "  already installed - skipping" -ForegroundColor Green
        continue
    }
    winget install --id $p.Id --exact --accept-package-agreements --accept-source-agreements
    if ($LASTEXITCODE -ne 0) { Write-Host "  install failed - do this one by hand" -ForegroundColor Yellow }
}

Write-Host ""
Write-Host "Note the PostgreSQL superuser password you set - setup-new-pc.ps1 asks for it." -ForegroundColor Yellow
'@ | Set-Content "$OutPath\reinstall-programs.ps1" -Encoding utf8
Ok "reinstall-programs.ps1 written"

# ------------------------------------------------------------------ report ---
# $args is a PowerShell automatic variable - naming a parameter that shadows it
# and breaks the call. Everything is resolved here rather than inside the
# here-string below, so no native command runs mid-template and leaves a
# stray non-zero $LASTEXITCODE behind.
function Ver ($cmd, $flag) {
    if (Get-Command $cmd -ErrorAction SilentlyContinue) {
        try { (& $cmd $flag | Select-Object -First 1) } catch { 'unknown' }
    } else { 'not installed' }
}

$nodeVer  = Ver node '-v'
$nodeArch = if (Get-Command node -ErrorAction SilentlyContinue) { node -p "process.arch" } else { 'n/a' }
$npmVer   = Ver npm '-v'
$gitVer   = Ver git '--version'
$osName   = (Get-CimInstance Win32_OperatingSystem).Caption
$psVer    = $PSVersionTable.PSVersion.ToString()
$pgVer    = ($apps | Where-Object { $_.DisplayName -match '^PostgreSQL' } | Select-Object -First 1).DisplayVersion
$codeVer  = ($apps | Where-Object { $_.DisplayName -match 'Visual Studio Code' } | Select-Object -First 1).DisplayVersion

@"
# Environment on the old PC

Captured $(Get-Date -Format 'yyyy-MM-dd HH:mm') from $env:COMPUTERNAME.

## Versions

| | |
|---|---|
| Windows | $osName |
| **CPU architecture** | **$env:PROCESSOR_ARCHITECTURE** |
| Node.js | $nodeVer ($nodeArch) |
| npm | $npmVer |
| Git | $gitVer |
| PostgreSQL | $pgVer |
| VS Code | $codeVer |
| PowerShell | $psVer |

## VS Code

$extCount extensions, listed in ``vscode-extensions.txt``. Settings, keybindings,
snippets and profiles are under ``vscode\``.

``restore-environment.ps1`` reinstalls the extensions and puts the settings back.

## Things that will not survive the move

**This machine is $env:PROCESSOR_ARCHITECTURE.** If the new PC is x64, download the x64
build of every tool - installers are not interchangeable. Node modules with
native components must be rebuilt, which a fresh ``npm install`` does anyway.

**HOMEDRIVE is ``H:``**, a mapped work drive. Git looks for its global config at
``H:\.gitconfig``, which does not exist, so there is no global git config at all -
git has been deriving your commit identity from the domain account. That is why
commits are authored as ``Tristan.Biro@lakesidefinancial.com.au``. On the new PC,
set it explicitly so commits are not attributed to the old firm:

``````powershell
git config --global user.name  "Tristan Biro"
git config --global user.email "tristan.biro26@gmail.com"
``````

**H:\ and L:\ are network drives** (roughly 642 GB each). Anything you keep on
them stays behind when you leave. Worth a look before your last day - this
migration only covers ``C:\FPGod-Program``.

**Claude Code credentials are not copied.** Sign in again on the new machine;
``.credentials.json`` is machine- and account-bound and is deliberately excluded.
Project settings and hooks live in the repo under ``.claude\`` and travel with it.

**Firm-managed software** (Teams add-ins, Outlook, anything the old IT team
pushed) is in ``installed-programs.csv`` for reference. The new firm's IT will
provision their own - do not try to carry licences across.
"@ | Set-Content "$OutPath\environment-report.md" -Encoding utf8
Ok "environment-report.md written"

exit 0
